### PR TITLE
GTM Hardcoded

### PR DESCRIPTION
**Pull request by jlazoff**
- [x] Install GTM
- [x] Change hardcoded GTM script to use package 
- [ ] Move GTM ID to env variable

### CODE REVIEW

**Review by jlazoff — COMMENTED** [review]
@tannn-younet @cuonglt-ync , please fix this issue and approve 🚀

**Comment by jlazoff** [comment]
Hi @EducationDAO ,
Can you help add the GTM ID env variable to the repo? 

**Next steps:**
- [ ] Install and test GTM 
- [ ] Move GTM ID to github repo env variable
- [ ] Change hardcoded GTM script to use package

**Comment by jlazoff** [comment]
Hi @EducationDAO ,

Please add a new repository secret NEXT_PUBLIC_GTM_ID with the value GTM-567GV6F

And merge PR for GTM to activate

**Comment by jlazoff** [comment]
Hi @kevin-chassagne ,
Are you able to approve this PR?

**Comment by jlazoff** [comment]
@kevin-chassagne ,
Since this is a public variable, I hardcode the ID for now:  GTM-567GV6F ✅ 

We will add this later: **_"Please add a new repository secret NEXT_PUBLIC_GTM_ID with the value GTM-567GV6F"_**

**Review by kevin-chassagne — APPROVED** [review]
LGTM!

**Pull request merged**
